# Generated by Django 3.0.7 on 2020-06-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200625_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='Skill',
        ),
        migrations.AddField(
            model_name='description',
            name='skill_level',
            field=models.IntegerField(choices=[(1, 'Fundamental Awareness'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
